matrix:
  include:
    - language: nix
      matrix:
        - os: linux
        - os: osx
    - language: python
      python: "3.6"
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script: pytest
    - language: python
      python: "3.7"
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script:
        - pytest
        - TEMCI_TEST_CMD=1 pytest
    - language: python
      python: "3.8"
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script:
        - pytest