matrix:
  include:
    - language: nix
      matrix:
        - os: linux
        - os: osx
    - language: python
      python:
        - "3.5"
        - "3.6"
        - "3.7"
      # command to install dependencies
      install:
        - pip3 install -e .
      # command to run tests
      script:
        - pytest
        - TEMCI_TEST_CMD=1 pytest