matrix:
  include:
    - language: nix
      os: linux
    - language: nix
      os: osx
    - language: nix
      os: windows
    - language: python
      python: "3.6"
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script: pytest
    - language: python
      python: "3.7"
      dist: xenial
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script:
        - pytest
        - TEMCI_TEST_CMD=1 pytest