matrix:
  include:
    - language: nix
      os: linux
      # work around weird `fetchGit` behavior...
      script: nix-build --arg src ./.
    - language: nix
      os: osx
      script: nix-build --arg src ./.
    - language: python
      python: "3.6"
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script: ./test.sh
    - language: python
      python: "3.7"
      dist: xenial
      install:
        - pip install --upgrade pip
        - pip3 install -e .
      script:
        - ./test.sh
        - TEMCI_TEST_CMD=1 ./test.sh
