 - attributes:
     description: 'hadori'
   run_config:
      run_cmd: 'hadori .'
   build_config:
      build_cmd: 'make'
      randomization:
        heap: 100
        stack: 100
        data: true
      number: 10